### ISSUE TITLE
Please implement option to specify the fields to return from JIRA in the search() method

### ISSUE THREAD

**Issue by SparklingSoftware** [chobie/jira-api-restclient#2] opened 2012-10-25 23:50 UTC
Hi,

Again: Awesome library! :-)

As a... developer 

I would like to... be able to specify the fields that will be returned by JIRA 
while calling the search method with a JQL statement.

so that... I can reduce the amount of data send across the network and therefore increase the website responsiveness.

Cheers,
Stephan

**Comment by aik099** [comment] 2016-02-27 09:02
Closing as the issue is now resolved.

**Closed by aik099** 2016-02-27 09:02 UTC
